### PR TITLE
add disconnect listener and emitter to socket

### PR DESCRIPTION
**Pull request by brandonkimmmm**
added disconnect listener and emitter for bot

### CODE REVIEW

**Comment by abeikverdi** [comment]
@brandonkimmmm  You can do this in a better way for example using removeEventListener and actually handling disconnects than just passing the word disconnect.
Additionally this disconnect you made is only added in "all" switch case. It can happen in user as well.

**Comment by brandonkimmmm** [comment]
@abeikverdi Socket.io already handles disconnects by attempting to reconnect. I'll make the socket emit an error when reconnection attempts fail but otherwise this disconnect event is only to notify robolla when it happens because robolla wasn't working properly even though reconnection was successful.

**Comment by abeikverdi** [comment]
I understand. We dont need to throw error in the socket.io. Instead of sending a disconnect message we need to handle the disconnection and reconnection logic using js event listener. Remember also this project is not just used for robolla.

**Comment by brandonkimmmm** [comment]
@abeikverdi By handling do you mean having the emitter wait until the reconnection is successful?

**Comment by brandonkimmmm** [comment]
@abeikverdi I made it so the listeners are removed on disconnect and reestablish when reconnect is successful

**Pull request merged**
